export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

export const LOAD_LESSONS_SUCCESS = 'LOAD_LESSONS_SUCCESS';
export const CREATE_LESSON_SUCCESS = 'CREATE_LESSON_SUCCESS';
export const UPDATE_LESSON_SUCCESS = 'UPDATE_LESSON_SUCCESS';

export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS';
export const UPDATE_ANSWER_SUCCESS = 'UPDATE_ANSWER_SUCCESS';

export const LOAD_QUIZZES_SUCCESS = 'LOAD_QUIZZES_SUCCESS';
export const CREATE_QUIZ_SUCCESS = 'CREATE_QUIZ_SUCCESS';
export const UPDATE_QUIZ_SUCCESS = 'UPDATE_QUIZ_SUCCESS';

export const LOAD_COURSEPAGES_SUCCESS = 'LOAD_COURSEPAGES_SUCCESS';
export const CREATE_COURSEPAGE_SUCCESS = 'CREATE_COURSEPAGE_SUCCESS';
export const UPDATE_COURSEPAGE_SUCCESS = 'UPDATE_COURSEPAGE_SUCCESS';



